unit TestCalendarDataSaver;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Classes, SysUtils, CalendarDataSaver, CalendarCommons, Windows;

type
  // Test methods for class TCalendarDataSaver

  TestTCalendarDataSaver = class(TTestCase)
  strict private
    FCalendarDataSaver: TCalendarDataSaver;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestWriteData;
    procedure TestBeginSave;
    procedure TestEndSave;
    procedure TestAddData;
  end;

implementation

procedure TestTCalendarDataSaver.SetUp;
begin
  FCalendarDataSaver := TCalendarDataSaver.Create('test.ics');
end;

procedure TestTCalendarDataSaver.TearDown;
begin
  FCalendarDataSaver.Free;
  FCalendarDataSaver := nil;
end;

procedure TestTCalendarDataSaver.TestWriteData;
var
  AData: string;
begin
  // TODO: Setup method call parameters
  FCalendarDataSaver.WriteData(AData);
  // TODO: Validate method results
end;

procedure TestTCalendarDataSaver.TestBeginSave;
begin
  FCalendarDataSaver.BeginSave;
  // TODO: Validate method results
end;

procedure TestTCalendarDataSaver.TestEndSave;
begin
  FCalendarDataSaver.EndSave;
  // TODO: Validate method results
end;

procedure TestTCalendarDataSaver.TestAddData;
var
  AData: TCalendarData;
begin
  // TODO: Setup method call parameters
  FCalendarDataSaver.AddData(AData);
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTCalendarDataSaver.Suite);
end.

